// Auto-generated from partition/AIR6010.csv
// DO NOT EDIT MANUALLY
// Generated by buildx.lua

#ifndef LUAT_PARTITION_MEM_AIR6010_H
#define LUAT_PARTITION_MEM_AIR6010_H

// AIR6010 (2048KB Flash)
#define LUAT_PARTITION_SECBOOT_ADDR          0x00000000U      // boot 分区偏移
#define LUAT_PARTITION_SECBOOT_SIZE          0x00010000U      // 64KB
#define LUAT_PARTITION_FOTA_ADDR             0x00010000U      // ota 分区偏移
#define LUAT_PARTITION_FOTA_SIZE             0x000C0000U      // 768KB
#define LUAT_PARTITION_APP_ADDR              0x000D0000U      // app 分区偏移
#define LUAT_PARTITION_APP_SIZE              0x00110000U      // 1088KB
#define LUAT_PARTITION_KV_ADDR               0x001E0000U      // data 分区偏移
#define LUAT_PARTITION_KV_SIZE               0x00010000U      // 64KB
#define LUAT_PARTITION_SYSPARAM_ADDR         0x001FE000U      // sysparam 分区偏移
#define LUAT_PARTITION_SYSPARAM_SIZE         0x00002000U      // 8KB

// 兼容旧代码的 KB 宏
#define LUAT_FS_SIZE                       (LUAT_PARTITION_FS_SIZE / 1024U)
#define LUAT_SCRIPT_SIZE                   (LUAT_PARTITION_SCRIPT_SIZE / 1024U)

#endif /* LUAT_PARTITION_MEM_AIR6010_H */
