// Auto-generated from partition/AIR6010.csv
// DO NOT EDIT MANUALLY
// Generated by project/spislave/buildx.lua

#ifndef LUAT_PARTITION_MEM_AIR6010_H
#define LUAT_PARTITION_MEM_AIR6010_H

// AIR6010 (1024KB Flash) - spislave 固件, 无 script 分区
#define LUAT_PARTITION_SECBOOT_ADDR          0x00000000U      // boot 偏移
#define LUAT_PARTITION_SECBOOT_SIZE          0x00010000U      // 64KB
#define LUAT_PARTITION_FOTA_ADDR             0x00010000U      // ota 偏移
#define LUAT_PARTITION_FOTA_SIZE             0x00050000U      // 320KB
#define LUAT_PARTITION_APP_ADDR              0x00060000U      // app 偏移
#define LUAT_PARTITION_APP_SIZE              0x00080000U      // 512KB
#define LUAT_PARTITION_KV_ADDR               0x000E0000U      // data 偏移
#define LUAT_PARTITION_KV_SIZE               0x00010000U      // 64KB
#define LUAT_PARTITION_FS_ADDR               0x000F0000U      // fs 偏移
#define LUAT_PARTITION_FS_SIZE               0x0000A000U      // 40KB
#define LUAT_PARTITION_SYSPARAM_ADDR         0x000FE000U      // sysparam 偏移
#define LUAT_PARTITION_SYSPARAM_SIZE         0x00002000U      // 8KB

// 兼容旧代码的 KB 宏
#define LUAT_FS_SIZE                       (LUAT_PARTITION_FS_SIZE / 1024U)

#endif /* LUAT_PARTITION_MEM_AIR6010_H */
